Programme : main.o AdresseInternet.o
		gcc AdresseInternet.o main.o -o Programme

main.o : main.c AdresseInternet.c
		gcc -c main.c -o main.o

AdresseInternet.o : AdresseInternet.c
		gcc -c AdresseInternet.c -o AdresseInternet.o